[build]
  command = "pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.10.0"
  PIP_VERSION = "21.0.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
